'use client';

import { useState, useRef, useEffect } from 'react';
import { Send, Mic, MicOff, Volume2, Loader2 } from 'lucide-react';
import { aiService } from '@/services/aiService';
import { ChatMessage } from '@/types';
import { useAI } from '@/context/AIContext';

export default function ChatInterface() {
  const { aiMode } = useAI();
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [inputValue, setInputValue] = useState('');
  const [isListening, setIsListening] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [recognition, setRecognition] = useState<SpeechRecognition | null>(null);
  const [isClient, setIsClient] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  // Initialize client-side only
  useEffect(() => {
    setIsClient(true);
    setMessages([
      {
        id: 'initial-0',
        type: 'assistant',
        content: `Hi! I'm your AI portfolio assistant. Ask me about your performance, top gainers, asset allocation, or any other portfolio questions.\n\nCurrently using: ${aiMode === 'gemini' ? 'Google Gemini' : aiMode === 'openai' ? 'OpenAI GPT' : 'REST API'} mode.`,
        timestamp: new Date()
      }
    ]);
  }, [aiMode]);

  useEffect(() => {
    if (!isClient) return;
    
    if (typeof window !== 'undefined' && 'webkitSpeechRecognition' in window) {
      const SpeechRecognition = window.webkitSpeechRecognition || window.SpeechRecognition;
      const recognitionInstance = new SpeechRecognition();
      recognitionInstance.continuous = false;
      recognitionInstance.interimResults = false;
      recognitionInstance.lang = 'en-US';
      
      recognitionInstance.onresult = (event) => {
        const transcript = event.results[0][0].transcript;
        setInputValue(transcript);
        setIsListening(false);
      };
      
      recognitionInstance.onerror = () => {
        setIsListening(false);
      };
      
      recognitionInstance.onend = () => {
        setIsListening(false);
      };
      
      setRecognition(recognitionInstance);
    }
  }, [isClient]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputValue.trim() || isLoading) return;

    const userMessageId = `user-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
    const userMessage: ChatMessage = {
      id: userMessageId,
      type: 'user',
      content: inputValue,
      timestamp: new Date()
    };

    setMessages(prev => [...prev, userMessage]);
    const queryText = inputValue;
    setInputValue('');
    setIsLoading(true);

    // 🔍 DEVELOPER LOGS
    console.log('💬 ChatInterface - User query submitted:');
    console.log('🎯 Query:', queryText);
    console.log('🤖 Selected AI Mode:', aiMode);
    console.log('🔑 Gemini configured:', !!process.env.NEXT_PUBLIC_GEMINI_API_KEY);

    try {
      // Process the query with AI service
      const intent = aiService.analyzeQuery(queryText);
      console.log('📊 Parsed intent:', intent);
      aiService.setMode(aiMode);
      const response = await aiService.generateResponse(queryText, intent);
      
      // Show which AI actually responded
      const modeUsed = response.aiMode || aiMode;
      response.content += `\n\n*Actually answered by: ${
        modeUsed === 'gemini' ? '🤖 Google Gemini AI' : '⚡ Pattern Matching'
      }*`;
      
      console.log('✅ Response generated by:', modeUsed);
      console.log('📝 Response preview:', response.content.substring(0, 100) + '...');
      
      setMessages(prev => [...prev, response]);
    } catch (error) {
      console.error('❌ Error generating response:', error);
      
      // Fallback error message
      const errorResponse: ChatMessage = {
        id: `error-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
        type: 'assistant',
        content: `Sorry, I encountered an error. Please try again or switch to Pattern Matching mode.\n\nError: ${error}`,
        timestamp: new Date()
      };
      setMessages(prev => [...prev, errorResponse]);
    } finally {
      setIsLoading(false);
    }
  };

  const startListening = () => {
    if (recognition && !isListening) {
      setIsListening(true);
      recognition.start();
    }
  };

  const stopListening = () => {
    if (recognition && isListening) {
      recognition.stop();
      setIsListening(false);
    }
  };

  const speakText = (text: string) => {
    if (!isClient || !('speechSynthesis' in window)) return;
    
    // If already speaking, stop and return
    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
      return;
    }
    
    const utterance = new SpeechSynthesisUtterance(text);
    utterance.rate = 0.9;
    utterance.pitch = 1;
    utterance.volume = 1;
    
    utterance.onstart = () => setIsSpeaking(true);
    utterance.onend = () => setIsSpeaking(false);
    utterance.onerror = () => setIsSpeaking(false);
    
    window.speechSynthesis.speak(utterance);
  };

  return (
    <div className="flex flex-col h-full max-h-screen">
      {/* Messages Container */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {isClient && messages.map((message) => (
          <div
            key={message.id}
            className={`flex ${message.type === 'user' ? 'justify-end' : 'justify-start'}`}
          >
            <div
              className={`max-w-[80%] p-3 rounded-lg ${
                message.type === 'user'
                  ? 'bg-blue-600 text-white'
                  : 'bg-gray-100 text-gray-900'
              }`}
            >
              <p className="whitespace-pre-wrap">{message.content}</p>
              {message.type === 'assistant' && (
                <div className="flex items-center mt-2 pt-2 border-t border-gray-200">
                  <button
                    onClick={() => speakText(message.content)}
                    className={`flex items-center gap-1 text-sm transition-colors ${
                      isSpeaking 
                        ? 'text-red-600 hover:text-red-800' 
                        : 'text-gray-600 hover:text-gray-800'
                    }`}
                  >
                    <Volume2 className="w-4 h-4" />
                    {isSpeaking ? 'Stop' : 'Listen'}
                  </button>
                </div>
              )}
            </div>
          </div>
        ))}
        {!isClient && (
          <div className="flex justify-start">
            <div className="max-w-[80%] p-3 rounded-lg bg-gray-100 text-gray-900">
              <p>Loading AI assistant...</p>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Input Form */}
      <div className="border-t bg-white p-4">
        <form onSubmit={handleSubmit} className="flex gap-2">
          <input
            ref={inputRef}
            type="text"
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            placeholder="Ask about your portfolio performance..."
            className="flex-1 p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-white text-gray-900 placeholder-gray-500"
          />
          <button
            type="button"
            onClick={isListening ? stopListening : startListening}
            className={`p-3 rounded-lg ${
              isListening
                ? 'bg-red-500 hover:bg-red-600 text-white'
                : 'bg-gray-500 hover:bg-gray-600 text-white'
            }`}
            disabled={!recognition}
          >
            {isListening ? <MicOff className="w-5 h-5" /> : <Mic className="w-5 h-5" />}
          </button>
          <button
            type="submit"
            disabled={!inputValue.trim() || isLoading}
            className="p-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:bg-gray-300 disabled:cursor-not-allowed flex items-center gap-2"
          >
            {isLoading ? (
              <Loader2 className="w-5 h-5 animate-spin" />
            ) : (
              <Send className="w-5 h-5" />
            )}
          </button>
        </form>
        
        {/* Quick Action Buttons */}
        <div className="flex flex-wrap gap-2 mt-3">
          <button
            onClick={() => setInputValue('How did my portfolio perform this week?')}
            className="px-3 py-2 text-sm bg-blue-50 text-blue-700 border border-blue-200 hover:bg-blue-100 hover:border-blue-300 rounded-full transition-colors font-medium"
          >
            Weekly Performance
          </button>
          <button
            onClick={() => setInputValue('Show me my top gainers today')}
            className="px-3 py-2 text-sm bg-green-50 text-green-700 border border-green-200 hover:bg-green-100 hover:border-green-300 rounded-full transition-colors font-medium"
          >
            Top Gainers
          </button>
          <button
            onClick={() => setInputValue('What is my asset allocation?')}
            className="px-3 py-2 text-sm bg-purple-50 text-purple-700 border border-purple-200 hover:bg-purple-100 hover:border-purple-300 rounded-full transition-colors font-medium"
          >
            Asset Allocation
          </button>
          <button
            onClick={() => setInputValue('Show me portfolio trends')}
            className="px-3 py-2 text-sm bg-orange-50 text-orange-700 border border-orange-200 hover:bg-orange-100 hover:border-orange-300 rounded-full transition-colors font-medium"
          >
            Portfolio Trends
          </button>
        </div>
      </div>
    </div>
  );
}